modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/yourusername/coremmaw/issues"

[[mods]]
modId="coremmaw"
version="1.0.0"
displayName="Core MMAW"
authors="IWOSS"
description='''
Мод запрещает рост культур в неподходящих биомах (Пустыни, Океаны и климатические несоответствия).
'''

[[dependencies.coremmaw]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.coremmaw]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.coremmaw]]
modId="geckolib"
mandatory=true
versionRange="[4.0,)"
ordering="AFTER"
side="BOTH"